export const directoryMembersRaw = [
  { sno: 1, businessName: 'Ranu Beauty Paurlor', ownerName: 'Ranu gupta', address: 'Suhag nagar, Firozaabad', udyamNumber: 'UDYAM-UP-27-0072078', category: 'Beauty Paurlour' },
  { sno: 2, businessName: 'Chanchal beautician', ownerName: 'Chanchal', address: 'Suhag nagar, Firozaabad', udyamNumber: 'UDYAM-UP-27-0072073', category: 'Beauty Paurlour' },
  { sno: 3, businessName: 'NEERU BEAUTY PAURLOR', ownerName: 'Neeru', address: 'Mehatab nagar', udyamNumber: 'UDYAM-UP-27-0064618', category: 'Beauty Paurlour' },
  { sno: 4, businessName: 'Soni beauty paurlor', ownerName: 'Soni Kumari', address: 'Station road, Firozabad', udyamNumber: 'Udyam-up-27-0060244', category: 'Beauty Paurlour' },
  { sno: 5, businessName: 'RAGINI BEAUTY PARLOUR', ownerName: 'Ragini', address: 'Sailai, Firozabad', udyamNumber: 'UDYAM-UP-27-0059407', category: 'Beauty Paurlour' },
  { sno: 6, businessName: 'RAKHI BEAUTY PAURLOR', ownerName: 'Rakhi', address: 'jalesar road, Firozabad', udyamNumber: 'UDYAM-UP-27-0059415', category: 'Beauty Paurlour' },
  { sno: 7, businessName: 'RACHNA BEAUTIPARLAR', ownerName: 'Rachana', address: 'Sailai, Firozabad', udyamNumber: 'UDYAM-UP-27-0062845', category: 'Beauty Paurlour' },
  { sno: 8, businessName: 'SVETA BEAUTY PARLOUR', ownerName: 'Sveta', address: 'Sailai, Firozabad', udyamNumber: 'UDYAM-UP-27-0063189', category: 'Beauty Paurlour' },
  { sno: 9, businessName: 'ANJALI BEAUTY PARLOUR', ownerName: 'Anjali', address: 'Sathi road Firozabad', udyamNumber: 'UDYAM-UP-27-0063191', category: 'Beauty Paurlour' },
  { sno: 10, businessName: 'MOHINI BEAUTY PAURLOR', ownerName: 'Mohini', address: 'samarat nagar, Firozabad', udyamNumber: 'UDYAM-UP-27-0063783', category: 'Beauty Paurlour' },
  { sno: 11, businessName: 'KIRAN BEAUTY PAURLOR', ownerName: 'Kiran', address: 'Nagla chota mirza, Firozaba', udyamNumber: 'UDYAM-UP-27-0063777', category: 'Beauty Paurlour' },
  { sno: 12, businessName: 'ANSHIKA BEAUTICIAN', ownerName: 'Anshika', address: 'Pratappura, Firozabad', udyamNumber: 'UDYAM-UP-27-0063897', category: 'Beauty Paurlour' },
  { sno: 13, businessName: 'MEERA BEAUTICIAN', ownerName: 'Meera', address: 'Pratappura, Firozabad', udyamNumber: 'UDYAM-UP-27-0063884', category: 'Beauty Paurlour' },
  { sno: 14, businessName: 'CHANDANI BEAUTY PAURLOUR', ownerName: 'Chandani', address: 'Sailai, Firozabad', udyamNumber: 'UDYAM-UP-27-0059807', category: 'Beauty Paurlour' },
  { sno: 15, businessName: 'NISHA BEAUTY PAURLAR', ownerName: 'Nisha', address: 'katra sunaran, Firozabad', udyamNumber: 'UDYAM-UP-27-0060179', category: 'Beauty Paurlour' },
  { sno: 16, businessName: 'LALETSH BEAUTY PARLOUR', ownerName: 'Laltesh', address: 'Himayunpur, Firozabad', udyamNumber: 'UDYAM-UP-27-0059795', category: 'Beauty Paurlour' },
  { sno: 17, businessName: 'TRAUN BEAUTY PAURLOUR', ownerName: 'Taruna', address: 'Himayunpur, Firozabad', udyamNumber: 'UDYAM-UP-27-0060546', category: 'Beauty Paurlour' },
  { sno: 18, businessName: 'SHWETA BEAUTY PAURLOR', ownerName: 'Sweta', address: 'Dolpura, Firozabad', udyamNumber: 'UDYAM-UP-27-0064376', category: 'Beauty Paurlour' },
  { sno: 19, businessName: 'ARTI BEAUTY PAURLOR', ownerName: 'Arti jain', address: 'Indra colony Firozabad', udyamNumber: 'UDYAM-UP-27-0072285', category: 'Beauty Paurlour' },
  { sno: 20, businessName: 'Shivani Beauty Paurlor', ownerName: 'Shivani jain', address: 'Indra colony Firozabad', udyamNumber: 'UDYAM-UP-27-0072086', category: 'Beauty Paurlour' },
  { sno: 21, businessName: 'Palak Beauty Paurlor', ownerName: 'Palak jain', address: 'Indra colony Firozabad', udyamNumber: 'UDYAM-UP-27-0072081', category: 'Beauty Paurlour' },
  { sno: 22, businessName: 'SHIVANI BEAUTY PAURLOR', ownerName: 'Shivani', address: 'karwala, Firozabad', udyamNumber: 'UDYAM-UP-27-0064612', category: 'Beauty Paurlour' },
  { sno: 23, businessName: 'MALA BEAUTY PAURLOR', ownerName: 'Mala Kushwa', address: 'Saraswati nagar, Firozabad', udyamNumber: 'UDYAM-UP-27-0064419', category: 'Beauty Paurlour' },
  { sno: 24, businessName: 'BHARTI MAKEUP ARTIST', ownerName: 'Bharti sharma', address: 'Om nagar, Firozabad', udyamNumber: 'UDYAM-UP-27-0064417', category: 'Beauty Paurlour' },
  { sno: 25, businessName: 'ARUSHI BEAUTY PAURLOR', ownerName: 'Arushi gupta', address: 'Hundawala baag, Firozabad', udyamNumber: 'UDYAM-UP-27-0064416', category: 'Beauty Paurlour' },
  { sno: 26, businessName: 'VANSHI BEAUTY PAURLOR', ownerName: 'Vanshika gup', address: 'Pameswar gate, Firozabad', udyamNumber: 'UDYAM-UP-27-0064415', category: 'Beauty Paurlour' },
  { sno: 27, businessName: 'NISHA BEAUTY PAURLOR', ownerName: 'Nisha', address: 'Kishan nagar, Firozabad', udyamNumber: 'UDYAM-UP-27-0064344', category: 'Beauty Paurlour' },
  { sno: 28, businessName: 'SHIVANI BEAUTY PAURLOR', ownerName: 'Shivani', address: 'Kishan nagar, Firozabad', udyamNumber: 'UDYAM-UP-27-0064228', category: 'Beauty Paurlour' },
  { sno: 29, businessName: 'NISHA BEAUTY PAURLAO', ownerName: 'Nisha', address: 'Kotla road, Firozabad', udyamNumber: 'UDYAM-UP-27-0064205', category: 'Beauty Paurlour' },
  { sno: 30, businessName: 'VINITA BEAUTY PAURLOR', ownerName: 'Vinita', address: 'Kotla road, Firozabad', udyamNumber: 'UDYAM-UP-27-0064210', category: 'Beauty Paurlour' },
  { sno: 31, businessName: 'VAISHNAVI BEAUTY PAURLOR', ownerName: 'Vaishnavi', address: 'Nagla mirza chota, Firozaba', udyamNumber: 'UDYAM-UP-27-0064203', category: 'Beauty Paurlour' },
  { sno: 32, businessName: 'DEEKSHA BEAUTY PAURLOR', ownerName: 'Deeksha', address: 'Pratappura, Firozabad', udyamNumber: 'UDYAM-UP-27-0063894', category: 'Beauty Paurlour' },
  { sno: 33, businessName: 'DURGESH BEAUTY PAURLOR', ownerName: 'Durgesh', address: 'Pratappura, Firozabad', udyamNumber: 'UDYAM-UP-27-0063893', category: 'Beauty Paurlour' },
  { sno: 34, businessName: 'ROSHANI BEAUTY PAURLOR', ownerName: 'Roshani', address: 'Pratappura, Firozabad', udyamNumber: 'UDYAM-UP-27-0063890', category: 'Beauty Paurlour' },
  { sno: 35, businessName: 'RACHANA BEAUTY PAURLOR', ownerName: 'Rachana', address: 'Pratappura, Firozabad', udyamNumber: 'UDYAM-UP-27-0063885', category: 'Beauty Paurlour' },
  { sno: 36, businessName: 'NEHA BEAUTY PAURLOR', ownerName: 'Neha kumari', address: 'Kishan nagar, Firozabad', udyamNumber: 'UDYAM-UP-27-0063786', category: 'Beauty Paurlour' },
  { sno: 37, businessName: 'LAXMI BEAUTY PAURLOR', ownerName: 'Laxmi', address: 'Mehatab nagar', udyamNumber: 'UDYAM-UP-27-0063774', category: 'Beauty Paurlour' },
  { sno: 38, businessName: 'AKANKSHA MAKEUP STUDIO', ownerName: 'Akanksha', address: 'tapa kala, Firozabad', udyamNumber: 'UDYAM-UP-27-0063771', category: 'Beauty Paurlour' },
  { sno: 39, businessName: 'SHIVANI BEAUTY PAURLOR', ownerName: 'Shivani yadav', address: 'Shahapur post jakhai, Firoza', udyamNumber: 'UDYAM-UP-27-0063768', category: 'Beauty Paurlour' },
  { sno: 40, businessName: 'ANITA BEAUTY MAKEUP', ownerName: 'Anita', address: 'Hari nagar, Firozabad', udyamNumber: 'UDYAM-UP-27-0060177', category: 'Beauty Paurlour' },
  { sno: 41, businessName: 'Somee Beautician', ownerName: 'Somee', address: 'Gazipur, Firozabad', udyamNumber: 'UDYAM-UP-27-0072557', category: 'Beauty Paurlour' },
  { sno: 42, businessName: 'Omvati Beautician', ownerName: 'Omvati', address: 'Gazipur, Firozabad', udyamNumber: 'UDYAM-UP-27-0072622', category: 'Beauty Paurlour' },
  { sno: 43, businessName: 'Pooja Beautician', ownerName: 'Pooja', address: 'katra sunaran, Firozabad', udyamNumber: 'UDYAM-UP-27-0072774', category: 'Beauty Paurlour' },
  { sno: 44, businessName: 'Reena garments', ownerName: 'Reena', address: 'Khergarh, Firozabad', udyamNumber: 'UDYAM-UP-27-0072844', category: 'Beauty Paurlour' },
  { sno: 45, businessName: 'M/S S.S.R BUILDING MATERIAL', ownerName: 'SHILENDRAK', address: 'Shikohabad, Firozabad', udyamNumber: 'UDYAM-UP-27-0057871', category: 'Building material' },
  { sno: 46, businessName: 'M/S DOLLY TRADERS', ownerName: 'Yogesh sharm', address: 'Near Bus stand, Firozabad', udyamNumber: 'UDYAM-UP-27-0046434', category: 'Cosmatic Products' },
  { sno: 47, businessName: 'PRINCI GARMENTS', ownerName: 'Princi', address: 'karwala, Firozabad', udyamNumber: 'UDYAM-UP-27-0069626', category: 'Garments Manufacturing' },
  { sno: 48, businessName: 'SHILPI TRADERS', ownerName: 'SHILPI', address: 'karwala, Firozabad', udyamNumber: 'UDYAM-UP-27-0069625', category: 'Garments Manufacturing' },
  { sno: 49, businessName: 'NANDINI GARMENTS', ownerName: 'Nandini kuma', address: 'Islam ganj Firozabad', udyamNumber: 'UDYAM-UP-27-0059405', category: 'Garments Manufacturing' },
  { sno: 50, businessName: 'VEERWATI SAREE CENTER', ownerName: 'Veerwati', address: 'Prem nagar Firozabad', udyamNumber: 'UDYAM-UP-27-0060283', category: 'Garments Manufacturing' },
  { sno: 51, businessName: 'ANJALI GARMENTS SHOP', ownerName: 'Anjali kumari', address: 'Sathi road Firozabad', udyamNumber: 'UDYAM-UP-27-0060282', category: 'Garments Manufacturing' },
  { sno: 52, businessName: 'PRACHI UDHYOD', ownerName: 'Pravesh', address: 'Himayunpur, Firozabad', udyamNumber: 'UDYAM-UP-27-0060279', category: 'Garments Manufacturing' },
  { sno: 53, businessName: 'SHILPI GARMENTS', ownerName: 'Shilpi', address: 'samarat nagar, Firozabad', udyamNumber: 'UDYAM-UP-27-0060266', category: 'Garments Manufacturing' },
  { sno: 54, businessName: 'NANDANI COLLECTION', ownerName: 'Nandani', address: 'karwala, Firozabad', udyamNumber: 'UDYAM-UP-27-0060269', category: 'Garments Manufacturing' },
  { sno: 55, businessName: 'MOHINI GARMENTS', ownerName: 'Mohini singh', address: 'purushottam nagar, Firozab', udyamNumber: 'UDYAM-UP-27-0068107', category: 'Garments Manufacturing' },
  { sno: 56, businessName: 'Anjali garments', ownerName: 'Anjali', address: 'bheem nagar, Firozabad', udyamNumber: 'UDYAM-UP-27-0067717', category: 'Garments Manufacturing' },
  { sno: 57, businessName: 'SHIVA GARMENTS', ownerName: 'Anjali', address: 'Kotla road, Firozabad', udyamNumber: 'UDYAM-UP-27-0060260', category: 'Garments Manufacturing' },
  { sno: 58, businessName: 'DEEKSHA GARMENTS', ownerName: 'Deeksha Push', address: 'Gandhi Nagar, Firozabad', udyamNumber: 'UDYAM-UP-27-0068111', category: 'Garments Manufacturing' },
  { sno: 59, businessName: 'KUMARI JI GARMENTS', ownerName: 'Manoj kumar', address: 'Nagla rati line par tundla', udyamNumber: 'UDYAM-UP-27-0067217', category: 'Garments Manufacturing' },
  { sno: 60, businessName: 'POOJA GARMENTS', ownerName: 'Pooja kumari', address: 'Chulawani, Tundla', udyamNumber: 'UDYAM-UP-27-0067532', category: 'Garments Manufacturing' },
  { sno: 61, businessName: 'SEEMENDER LEATHER PRODUCT', ownerName: 'Seemendra k', address: 'Anwara road Tundla', udyamNumber: 'UDYAM-UP-27-0067214', category: 'Garments Manufacturing' },
  { sno: 62, businessName: 'CHANCHAL GARMENTS', ownerName: 'Chanchal', address: 'Nagla maszid line par tundl', udyamNumber: 'UDYAM-UP-27-0067530', category: 'Garments Manufacturing' },
  { sno: 63, businessName: 'KAJAL GARMENTS', ownerName: 'Kajal', address: 'Anwara road Tundla', udyamNumber: 'UDYAM-UP-27-0067538', category: 'Garments Manufacturing' },
  { sno: 64, businessName: 'SHIKHA GARMENTS', ownerName: 'Shikha gautam', address: 'Nagla jamman par, Tundla', udyamNumber: 'UDYAM-UP-27-0067074', category: 'Garments Manufacturing' },
  { sno: 65, businessName: 'KRISHNA GARMENTS', ownerName: 'Km krishna', address: 'Anwara road Tundla', udyamNumber: 'UDYAM-UP-27-0067637', category: 'Garments Manufacturing' },
  { sno: 66, businessName: 'VARSHA GARMENTS', ownerName: 'Varsha', address: 'Sirmai kanvara Firozabad', udyamNumber: 'UDYAM-UP-27-0062593', category: 'Garments Manufacturing' },
  { sno: 67, businessName: 'SONAM GARMENTS', ownerName: 'Sonam', address: 'Nagla himmat, Firozabad', udyamNumber: 'UDYAM-UP-27-0062572', category: 'Garments Manufacturing' },
  { sno: 68, businessName: 'TULSHI SAILAI CENTER', ownerName: 'Tulshi', address: 'Nagla himmat, Firozabad', udyamNumber: 'UDYAM-UP-27-0062587', category: 'Garments Manufacturing' },
  { sno: 69, businessName: 'NAINSI BOUTIQUE', ownerName: 'Nainsi', address: 'Nagla himmat, Firozabad', udyamNumber: 'UDYAM-UP-27-0062575', category: 'Garments Manufacturing' },
  { sno: 70, businessName: 'SADHANA GARMENTS', ownerName: 'Sadhana saga', address: 'Nagla himmat, Firozabad', udyamNumber: 'UDYAM-UP-27-0062599', category: 'Garments Manufacturing' },
  { sno: 71, businessName: 'PRIYANSHI GARMENTS', ownerName: 'Priyanshi', address: 'Khergarh, Firozabad', udyamNumber: 'UDYAM-UP-27-0067675', category: 'Garments Manufacturing' },
  { sno: 72, businessName: 'PRIYANSHI GARMENTS', ownerName: 'Priyanshi', address: 'Khergarh, Firozabad', udyamNumber: 'UDYAM-UP-27-0067616', category: 'Garments Manufacturing' },
  { sno: 73, businessName: 'POONAM GARMENTS', ownerName: 'Poonam', address: 'Khergarh, Firozabad', udyamNumber: 'UDYAM-UP-27-0067518', category: 'Garments Manufacturing' },
  { sno: 74, businessName: 'INDRAPAL JI KI KAPDE KI DUKAN', ownerName: 'Indra pal', address: 'Khergarh, Firozabad', udyamNumber: 'UDYAM-UP-27-0067521', category: 'Garments Manufacturing' },
  { sno: 75, businessName: 'ROHIT GARMENTS', ownerName: 'Rohit kumar', address: 'Khergarh, Firozabad', udyamNumber: 'UDYAM-UP-27-0067656', category: 'Garments Manufacturing' },
  { sno: 76, businessName: 'SHASHI GARMENTS', ownerName: 'Shashi', address: 'Himayunpur, Firozabad', udyamNumber: 'UDYAM-UP-27-0061435', category: 'Garments Manufacturing' },
  { sno: 77, businessName: 'SONAM GARMENTS', ownerName: 'Sonam', address: 'jalesar road, Firozabad', udyamNumber: 'UDYAM-UP-27-0063917', category: 'Garments Manufacturing' },
  { sno: 78, businessName: 'RACHANA SAILAI CENTER', ownerName: 'Rachana', address: 'jalesar road, Firozabad', udyamNumber: 'UDYAM-UP-27-0063916', category: 'Garments Manufacturing' },
  { sno: 79, businessName: 'LAXMI GARMENTS', ownerName: 'Laxmi', address: 'jalesar road, Firozabad', udyamNumber: 'UDYAM-UP-27-0063912', category: 'Garments Manufacturing' },
  { sno: 80, businessName: 'SHIV INSTITUTE OF EDUCATION', ownerName: 'Manju bharti', address: 'Pratappura, Firozabad', udyamNumber: 'UDYAM-UP-27-0059397', category: 'Garments Manufacturing' },
  { sno: 81, businessName: 'DOLLY GARMENTS', ownerName: 'Dolly', address: 'Mohalla kheda, Firozabad', udyamNumber: 'UDYAM-UP-27-0064423', category: 'Garments Manufacturing' },
  { sno: 82, businessName: 'RIYA GARMENTS', ownerName: 'Riya singh', address: 'samarat nagar, Firozabad', udyamNumber: 'UDYAM-UP-27-0064383', category: 'Garments Manufacturing' },
  { sno: 83, businessName: 'K Daughter Enterprises', ownerName: 'Deepti sharm', address: 'Himayunpur, Firozabad', udyamNumber: 'UDYAM-UP-27-0071323', category: 'Garments Manufacturing' },
  { sno: 84, businessName: 'DEEKSHA GARMENTS', ownerName: 'Deeksha', address: 'Dev nagar, Firozabad', udyamNumber: 'UDYAM-UP-27-0071304', category: 'Garments Manufacturing' },
  { sno: 85, businessName: 'Ragini Garments', ownerName: 'Ragini yadav', address: 'Khergarh, Firozabad', udyamNumber: 'UDYAM-UP-27-0067525', category: 'Garments Manufacturing' },
  { sno: 86, businessName: 'ANJALI SHARMA', ownerName: 'Anjali sharma', address: 'Jain nagar, Firozabad', udyamNumber: 'UDYAM-UP-27-0045230', category: 'Garments Manufacturing' },
  { sno: 87, businessName: 'NEELAM GARMENTS', ownerName: 'Neelam', address: 'Suhag nagar, Firozaabad', udyamNumber: 'UDYAM-UP-27-0064427', category: 'Garments Manufacturing' },
  { sno: 88, businessName: 'LATASHA SAILAI CENTER', ownerName: 'Latasha bagh', address: 'Suhag nagar, Firozaabad', udyamNumber: 'UDYAM-UP-27-0064425', category: 'Garments Manufacturing' },
  { sno: 89, businessName: 'SIMMI GARMENTS', ownerName: 'Simmi', address: 'katra sunaran, Firozabad', udyamNumber: 'UDYAM-UP-27-0064411', category: 'Garments Manufacturing' },
  { sno: 90, businessName: 'VARISHA GARMENTS', ownerName: 'Varisha', address: 'katra sunaran, Firozabad', udyamNumber: 'UDYAM-UP-27-0064391', category: 'Garments Manufacturing' },
  { sno: 91, businessName: 'SAKSHI GARMENTS', ownerName: 'Sakshi sharm', address: 'Bus stand ke samne, Firoza', udyamNumber: 'UDYAM-UP-27-0064386', category: 'Garments Manufacturing' },
  { sno: 92, businessName: 'PRINCY GARMENTS', ownerName: 'Princy', address: 'Daulatpur, Firozabad', udyamNumber: 'UDYAM-UP-27-0064385', category: 'Garments Manufacturing' },
  { sno: 93, businessName: 'ANCHAL SAILAI CENTER', ownerName: 'Anchal verma', address: 'karwala, Firozabad', udyamNumber: 'UDYAM-UP-27-0064384', category: 'Garments Manufacturing' },
  { sno: 94, businessName: 'TANYA GARMENTS', ownerName: 'Tanya parash', address: 'Suhag nagar, Firozaabad', udyamNumber: 'UDYAM-UP-27-0064373', category: 'Garments Manufacturing' },
  { sno: 95, businessName: 'AASHIKA GARMENTS', ownerName: 'Aashika Gupt', address: 'Ram nagra Firozabaf', udyamNumber: 'UDYAM-UP-27-0064367', category: 'Garments Manufacturing' },
  { sno: 96, businessName: 'JAHANVI GARMENTS', ownerName: 'Jahanvi gupta', address: 'Suhag nagar, Firozaabad', udyamNumber: 'UDYAM-UP-27-0064365', category: 'Garments Manufacturing' },
  { sno: 97, businessName: 'MAHAK GARMENT', ownerName: 'Mahak gupta', address: 'Ram nagra Firozabaf', udyamNumber: 'UDYAM-UP-27-0064359', category: 'Garments Manufacturing' },
  { sno: 98, businessName: 'SAPNA GARMENTS', ownerName: 'Sapna', address: 'Ram nagra Firozabaf', udyamNumber: 'UDYAM-UP-27-0064346', category: 'Garments Manufacturing' },
  { sno: 99, businessName: 'NEELAM GARMENTS', ownerName: 'Neelam', address: 'jalesar road, Firozabad', udyamNumber: 'UDYAM-UP-27-0063922', category: 'Garments Manufacturing' },
  { sno: 100, businessName: 'ALAKA GARMENTS', ownerName: 'Alaka', address: 'Khergarh, Firozabad', udyamNumber: 'UDYAM-UP-27-0062600', category: 'Garments Manufacturing' },
  { sno: 101, businessName: 'ANUSHKA SAILAI CENTER', ownerName: 'Anushka', address: 'Khergarh, Firozabad', udyamNumber: 'UDYAM-UP-27-0062598', category: 'Garments Manufacturing' },
  { sno: 102, businessName: 'DURGESH GARMENT', ownerName: 'Durgesh', address: 'Khergarh, Firozabad', udyamNumber: 'UDYAM-UP-27-0062591', category: 'Garments Manufacturing' },
  { sno: 103, businessName: 'SULEKHA GARMENTS', ownerName: 'Sulekha', address: 'Khergarh, Firozabad', udyamNumber: 'UDYAM-UP-27-0062584', category: 'Garments Manufacturing' },
  { sno: 104, businessName: 'THAKUR JI BOUTIQUE', ownerName: 'Neha', address: 'Khergarh, Firozabad', udyamNumber: 'UDYAM-UP-27-0062564', category: 'Garments Manufacturing' },
  { sno: 105, businessName: 'SHIVAM GARMENTS', ownerName: 'Shivam rajpo', address: 'Gazipur, Firozabad', udyamNumber: 'UDYAM-UP-27-0061902', category: 'Garments Manufacturing' },
  { sno: 106, businessName: 'AAKASH LEHENGA GARMENTS', ownerName: 'Akash kumar', address: 'Gazipur, Firozabad', udyamNumber: 'UDYAM-UP-27-0061897', category: 'Garments Manufacturing' },
  { sno: 107, businessName: 'CHHITORIA BIOTIOQUE', ownerName: 'Rajani', address: 'Himayunpur, Firozabad', udyamNumber: 'UDYAM-UP-27-0061883', category: 'Garments Manufacturing' },
  { sno: 108, businessName: 'MAA VAISHNO DEVI', ownerName: 'Sudha devi', address: 'Raipura road, Firozabad', udyamNumber: 'UDYAM-UP-27-0051693', category: 'Garments Manufacturing' },
  { sno: 109, businessName: 'REKHA GARMENTS', ownerName: 'Rekha', address: 'Himayunpur, Firozabad', udyamNumber: 'UDYAM-UP-27-0061448', category: 'Garments Manufacturing' },
  { sno: 110, businessName: 'Parihar garments', ownerName: 'Pooja', address: 'Himayunpur, Firozabad', udyamNumber: 'UDYAM-UP-27-0061444', category: 'Garments Manufacturing' },
  { sno: 111, businessName: 'Jyoti Sailai center', ownerName: 'Jyoti', address: 'Himayunpur, Firozabad', udyamNumber: 'UDYAM-UP-27-0061441', category: 'Garments Manufacturing' },
  { sno: 112, businessName: 'Komal sailai center', ownerName: 'Komal', address: 'Himayunpur, Firozabad', udyamNumber: 'UDYAM-UP-27-0061428', category: 'Garments Manufacturing' },
  { sno: 113, businessName: 'Komal chaturvedi garments man', ownerName: 'Komal chatur', address: 'Himayunpur, Firozabad', udyamNumber: 'UDYAM-UP-27-0061422', category: 'Garments Manufacturing' },
  { sno: 114, businessName: 'Tanya garments', ownerName: 'Tanya pandy', address: 'Dabrai, Firozabad', udyamNumber: 'UDYAM-UP-27-0072395', category: 'Garments Manufacturing' },
  { sno: 115, businessName: 'Sudha Garments', ownerName: 'Sudha', address: 'Ram nagra Firozabad', udyamNumber: 'UDYAM-UP-27-0072393', category: 'Garments Manufacturing' },
  { sno: 116, businessName: 'Parul Garments', ownerName: 'Parul', address: 'katra sunaran, Firozabad', udyamNumber: 'UDYAM-UP-27-0072561', category: 'Garments Manufacturing' },
  { sno: 117, businessName: 'Alpana garments', ownerName: 'Alpana', address: 'Ram nagra Firozabad', udyamNumber: 'UDYAM-UP-27-0072836', category: 'Garments Manufacturing' },
  { sno: 118, businessName: 'Sugandh Garments', ownerName: 'Sugandh khan', address: 'choki gate Circular road firo', udyamNumber: 'UDYAM-UP-27-0072839', category: 'Garments Manufacturing' },
  { sno: 119, businessName: 'Radhey Enterprises', ownerName: 'Goinka', address: 'Ram nagra Firozabaf', udyamNumber: 'UDYAM-UP-27-0053529', category: 'Glass Bangles' },
  { sno: 120, businessName: 'SONAM GLASS HANDICRAFT', ownerName: 'Sonam', address: 'Nagla karan singh', udyamNumber: 'UDYAM-UP-27-0046629', category: 'Glass Handi craft' },
  { sno: 121, businessName: 'Sanchita Glass handi craft', ownerName: 'Sanchita jain', address: 'Indra colony, Firozabad', udyamNumber: 'UDYAM-UP-27-0046165', category: 'Glass Handi craft' },
  { sno: 122, businessName: 'RAJ VERMA MALA DORI', ownerName: 'Raj kumar', address: 'Kotla road, Firozabad', udyamNumber: 'UDYAM-UP-27-0061765', category: 'Jewellary Making' },
  { sno: 123, businessName: 'UMA JEWELLARY', ownerName: 'Lalit verma', address: 'Kotla road, Firozabad', udyamNumber: 'UDYAM-UP-27-0061758', category: 'Jewellary Making' },
  { sno: 124, businessName: 'SHRIJI JEWELLERS', ownerName: 'Vishnu verma', address: 'Nai basti, Firozabad', udyamNumber: 'UDYAM-UP-27-0061754', category: 'Jewellary Making' },
  { sno: 125, businessName: 'VANSH JEWELLERS', ownerName: 'Manoj verma', address: 'Nai basti, Firozabad', udyamNumber: 'UDYAM-UP-27-0061753', category: 'Jewellary Making' },
  { sno: 126, businessName: 'M/S GAURAV JEWELLERS', ownerName: 'Gaurav verma', address: 'Ghanta ghar, Firozabad', udyamNumber: 'UDYAM-UP-27-0002134', category: 'Jewellary Making' },
  { sno: 127, businessName: 'HERO SAILAI', ownerName: 'Rajesh verma', address: 'Nai basti, Firozabad', udyamNumber: 'UDYAM-UP-27-0061749', category: 'Jewellery Making' },
  { sno: 128, businessName: 'SONU ANGUTI WALE', ownerName: 'Siddarth verm', address: 'Krishna pada, Firozabad', udyamNumber: 'UDYAM-UP-27-0061746', category: 'Jewellary Making' },
  { sno: 129, businessName: 'DEVENDRA MOTI PUWAI WALE', ownerName: 'Yogendra ver', address: 'Nai basti, Firozabad', udyamNumber: 'UDYAM-UP-27-0061745', category: 'Jewellary Making' },
  { sno: 130, businessName: 'MAA KELA DEVI JEWELLERS', ownerName: 'krishna verm', address: 'Nai basti, Firozabad', udyamNumber: 'UDYAM-UP-27-0061744', category: 'Jewellary Making' },
  { sno: 131, businessName: 'SHRI DURGA DAICUTTERS', ownerName: 'Keshav verma', address: 'Nai basti, Firozabad', udyamNumber: 'UDYAM-UP-27-0061743', category: 'Jewellary Making' },
  { sno: 132, businessName: 'DHARMENDRA JWELLERY', ownerName: 'Dharmendra', address: 'Krishna pada, Firozabad', udyamNumber: 'UDYAM-UP-27-0055794', category: 'Jewellary Making' },
  { sno: 133, businessName: 'G.V GOLDSMITH', ownerName: 'Lal singh verm', address: 'Mohalla greya, Firozabad', udyamNumber: 'UDYAM-UP-27-0061740', category: 'Jewellery Making' },
  { sno: 134, businessName: 'PRINCE VERMA GOLDSMITH', ownerName: 'Prince verma', address: 'Nai basti, Firozabad', udyamNumber: 'UDYAM-UP-27-0061736', category: 'Jewellary Making' },
  { sno: 135, businessName: 'KRISHNA PADA GOLDSMITH', ownerName: 'Jitendra kum', address: 'Nai basti, Firozabad', udyamNumber: 'UDYAM-UP-27-0061733', category: 'Jewellary Making' },
  { sno: 136, businessName: 'RAM SHYAM UJALA POLICE', ownerName: 'Shyam verma', address: 'Ghanta ghar, Firozabad', udyamNumber: 'UDYAM-UP-27-0059355', category: 'Jewellary Making' },
  { sno: 137, businessName: 'GOPAL JEWELRY', ownerName: 'Gopal', address: 'Nai basti, Firozabad', udyamNumber: 'UDYAM-UP-27-0061730', category: 'Jewellary Making' },
  { sno: 138, businessName: 'KRISHNA JEWELLERY', ownerName: 'Pannalal verm', address: 'Krishna pada, Firozabad', udyamNumber: 'UDYAM-UP-27-0047370', category: 'Jewellary Making' },
  { sno: 139, businessName: 'SIDDART JAWLLERS', ownerName: 'Anuj singh', address: 'Nai basti, Firozabad', udyamNumber: 'UDYAM-UP-27-0061729', category: 'Jewellary Making' },
  { sno: 140, businessName: 'SONU VERMA GOLDSMITH', ownerName: 'Krishna kuma', address: 'Nai basti, Firozabad', udyamNumber: 'UDYAM-UP-27-0061724', category: 'Jewellary Making' },
  { sno: 141, businessName: 'AVANEESH KIRANA STORE', ownerName: 'AVANEESH KU', address: 'Shikohabad, Firozabad', udyamNumber: 'UDYAM-UP-27-0057063', category: 'Food products' },
  { sno: 142, businessName: 'USHA KIRANA STORE', ownerName: 'Usha devi', address: 'tapa kala, Firozabad', udyamNumber: 'UDYAM-UP-27-0061664', category: 'Food products' },
  { sno: 143, businessName: 'LACHHMI KIRANA STORE', ownerName: 'Lachhami', address: 'Kotla road, Firozabad', udyamNumber: 'UDYAM-UP-27-0037870', category: 'Food products' },
  { sno: 144, businessName: 'MOHINI ADVENCED INSTITUTE', ownerName: 'mohini shank', address: 'chauban mohalla, Firozabad', udyamNumber: 'UDYAM-UP-27-0059960', category: 'Leather Goods Products' },
  { sno: 145, businessName: 'RASHMI LAGHU UDHYOG', ownerName: 'Rashmi kuma', address: 'purushottam nagar, Firozab', udyamNumber: 'UDYAM-UP-27-0060274', category: 'Leather Goods Products' },
  { sno: 146, businessName: 'ARYAN MEDICAL POINT', ownerName: 'Aryan kumar', address: 'Mohalla kheda, Firozabad', udyamNumber: 'UDYAM-UP-27-0060005', category: 'Leather Goods Products' },
  { sno: 147, businessName: 'TANISHA LEATHER PRODUCT', ownerName: 'Tanisha shank', address: 'chauban mohalla, Firozabad', udyamNumber: 'UDYAM-UP-27-0059972', category: 'Leather Goods Products' },
  { sno: 148, businessName: 'AKASH ENTERPRISES', ownerName: 'Akash shankh', address: 'chauban mohalla, Firozabad', udyamNumber: 'UDYAM-UP-27-0059954', category: 'Leather Goods Products' },
  { sno: 149, businessName: 'M.K ENTERPRISE', ownerName: 'Mohit kumar', address: 'purushottam nagar, Firozab', udyamNumber: 'UDYAM-UP-27-0068150', category: 'Leather Goods Products' },
  { sno: 150, businessName: 'ANIL ENTERPRISES', ownerName: 'Anil kumar', address: 'samarat nagar, Firozabad', udyamNumber: 'UDYAM-UP-27-0060294', category: 'Leather Goods Products' },
  { sno: 151, businessName: 'SONY LAGHU UDHYOG', ownerName: 'Sony', address: 'Gauch, Firozabad', udyamNumber: 'UDYAM-UP-27-0058473', category: 'Leather Goods Products' },
  { sno: 152, businessName: 'ADVANCE TREDARS', ownerName: 'Bhudevi', address: 'Lalgadi, Firozabad', udyamNumber: 'UDYAM-UP-27-0058476', category: 'Leather Goods Products' },
  { sno: 153, businessName: 'VILSON LEATHER PRODUCT', ownerName: 'Vilson kumar', address: 'samarat nagar, Firozabad', udyamNumber: 'UDYAM-UP-27-0060263', category: 'Leather Goods Products' },
  { sno: 154, businessName: 'M.S ENTERPRISES', ownerName: 'Manish', address: 'Shyam nagar, Firozabad', udyamNumber: 'UDYAM-UP-27-0059964', category: 'Leather Goods Products' },
  { sno: 155, businessName: 'S.M ENTERPRISES', ownerName: 'Saunu', address: 'Shyam nagar, Firozabad', udyamNumber: 'UDYAM-UP-27-0059966', category: 'Leather Goods Products' },
  { sno: 156, businessName: 'KAVITA THE DREAM SHOP', ownerName: 'Kavita kishor', address: 'Mathura nagar, Firozabad', udyamNumber: 'UDYAM-UP-27-0060277', category: 'Leather Goods Products' },
  { sno: 157, businessName: 'SAKSHI ENTERPRISES', ownerName: 'sakshi varun', address: 'karwala, Firozabad', udyamNumber: 'UDYAM-UP-27-0068355', category: 'Leather Goods Products' },
  { sno: 158, businessName: 'PRIYA TRADERS', ownerName: 'Priya', address: 'Mohammadpur, Firozabad', udyamNumber: 'UDYAM-UP-27-0069101', category: 'Leather Goods Products' },
  { sno: 159, businessName: 'RUBI LEATHER PRODUCT', ownerName: 'Rubi devi', address: 'Nagla jamman par, Tundla', udyamNumber: 'UDYAM-UP-27-0067070', category: 'Leather Goods Products' },
  { sno: 160, businessName: 'SUBODH ENTERPRISES', ownerName: 'Subodh kuma', address: 'Anwara road Tundla', udyamNumber: 'UDYAM-UP-27-0067610', category: 'Leather Goods Products' },
  { sno: 161, businessName: 'ABNISH GARMENTS', ownerName: 'Abnish kuma', address: 'Anwara road Tundla', udyamNumber: 'UDYAM-UP-27-0067130', category: 'Leather Goods Products' },
  { sno: 162, businessName: 'HIMANSHU LEATHER PRODUCT', ownerName: 'Himanshu', address: 'M P road Tundla', udyamNumber: 'UDYAM-UP-27-0067692', category: 'Leather Goods Products' },
  { sno: 163, businessName: 'SHIVANI LEATHER PRODUCT', ownerName: 'shivani', address: 'Chulawani, Tundla', udyamNumber: 'UDYAM-UP-27-0067134', category: 'Leather Goods Products' },
  { sno: 164, businessName: 'SWARTHI LEATHER PRODUCT', ownerName: 'Swarthi maho', address: 'Sirsaganj, Tundla', udyamNumber: 'UDYAM-UP-27-0067531', category: 'Leather Goods Products' },
  { sno: 165, businessName: 'NATASHA LEATHER PRODUCT', ownerName: 'Natasha nigu', address: 'Khergarh, Firozabad', udyamNumber: 'UDYAM-UP-27-0067658', category: 'Leather Goods Products' },
  { sno: 166, businessName: 'GUNJAN LEATHER PRODUCT', ownerName: 'Gunjan', address: 'bheem nagar, Firozabad', udyamNumber: 'UDYAM-UP-27-0067719', category: 'Leather Goods Products' },
  { sno: 167, businessName: 'Ambuj traders', ownerName: 'Ambuj', address: 'Mahaveer nagar', udyamNumber: 'UDYAM-UP-27-0065757', category: 'Leather Goods Products' },
  { sno: 168, businessName: 'Gupta shoes store', ownerName: 'Roni rapuriya', address: 'jalesar road, Firozabad', udyamNumber: 'UDYAM-UP-27-0072710', category: 'Leather Goods Products' },
  { sno: 169, businessName: 'ASHOK PLASTIC STORE', ownerName: 'Praveen kum', address: 'Ganj mohalla, Firozabad', udyamNumber: 'UDYAM-UP-27-0034848', category: 'Plastic materials' },
  { sno: 170, businessName: 'BHADAURIYA CONTRACTOR & SU', ownerName: 'Ram shankar', address: 'Charbhag, Firozabad', udyamNumber: 'UDYAM-UP-27-0020378', category: 'Building construction' }
];
